version: 2.1
executors:
  node12-executor:
    docker:
      - image: node:12-alpine3.11
      
jobs:
  build:
    executor: node12-executor
    steps:
      - checkout
      - run: |
          npm install
          npm build
  test:
    executor: node12-executor
    steps:
      - checkout
      - run: |
          npm install
          npm run test

workflows:
  push-workflow:
    jobs:
      - build
      - test
